CREATE TABLE `vo_place` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `place_status` varchar(50) CHARACTER SET utf8 NOT NULL,
 `title` varchar(100) CHARACTER SET utf8 NOT NULL,
 `content` text CHARACTER SET utf8,
 `category` varchar(50) CHARACTER SET utf8 DEFAULT NULL,
 `author` varchar(50) CHARACTER SET utf8 DEFAULT NULL,
 `date_created` datetime NOT NULL,
 `date_updated` datetime DEFAULT NULL,
 `location` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
 `phone_number` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
 `mobile_number` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
 `email` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
 `website` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
 `rating` float DEFAULT NULL,
 `when_to_go` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
 `budget` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
 `which_mood` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
 `to_go_with` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
 `reservation` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
 `cuisine` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
 `remarks` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
 `meta_title` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
 `meta_description` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
 `entity_status` varchar(50) CHARACTER SET utf8 NOT NULL,
 PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=latin1
